# Task 1:

1. Write a function to compute 5/0 and use try/except to catch the exceptions.


In [10]:
def division(x,y):
    try:
        result = x/y
        print(result)
    except ZeroDivisionError:
        print("division by zero not possible!")


In [11]:
division(5,3)

1.6666666666666667


In [12]:
division(5,0)

division by zero not possible!


2.  Implement a Python program to generate all sentences where subject is in 

["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [13]:
subject=["Americans","Indians"]
verb=["play","watch"]
objects=["baseball","cricket"]

for i in subject:
    for j in verb:
        for k in objects:
            print(i+" "+j+" "+k)

Americans play baseball
Americans play cricket
Americans watch baseball
Americans watch cricket
Indians play baseball
Indians play cricket
Indians watch baseball
Indians watch cricket


# Task 2:

1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.


HINT: Such a matrix with a geometric progression in each row is named for Alexandre-heophile Vandermonde.

In [26]:
row = input("Enter the number array seperated by comma: ").split(",")
column = input("Enter the power factor: ")

Enter the number array seperated by comma: 1,2,3,4,5,6
Enter the power factor: 4


In [27]:
import numpy as np 
def matrix(m,n):
    a=0
    b=0
    z=np.zeros((len(m),int(n)))
    for i in m:
        for j in range(int(n)):
            z[a][b] = int(i)**j
            b+=1
        a+=1
        b=0
    return z

In [28]:
print(matrix(row,column))

[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]
 [  1.   6.  36. 216.]]
